#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix run \
    --ignore-environment \
    --file 'nix/sources' \
    nix-project-exe \
    --command \
    nix-project \
    --upgrade \
    --source-dir 'nix/sources' \
    --nix "$(command -v nix)" \
    "$@"
