#!/bin/sh -eu

cd "$(dirname "$0")/.."

# DESIGN: the `pkgs.coreutils` argument makes utilities like `whoami` available
# for evaluated code blocks. This is just an example, you can include any
# package you like.
nix run \
    --ignore-environment \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    --file 'nix/sources' \
    nix-project-org2gfm \
    pkgs.coreutils \
    --command org2gfm --evaluate "$@"
