#!/bin/sh -eu

cd "$(dirname "$0")/.."

# DESIGN: the `pkgs.coreutils` argument makes utilities like `whoami` available
# for evaluated code blocks. This is just an example, you can include any
# package you like.
nix run \
    --ignore-environment \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    --file nix \
    nixpkgs-stable.bash \
    nixpkgs-stable.coreutils \
    nixpkgs-stable.gnugrep \
    nixpkgs-stable.nix-project-org2gfm \
    nixpkgs-stable.tree \
    nixpkgs-unstable.ansifilter \
    --command \
    org2gfm \
    --ignore links.org \
    --nix "$(command -v nix)" \
    --evaluate \
    "$@"
